__name__ = 'churnr'
__description__ = 'The churning detection app'
__author__ = 'Helder Martins'
__email__ = 'heldergaray@gmail.com'
__url__ = 'https://github.com/helderm/churnr'
__version__ = '0.5.0'
